config/routes.rb
Rails.application.routes.draw do
  
  get 'contacts', to: "contacts#index"

  resources :posts
  resources :home do
    resources :posts
  end
	get 'profile', to: 'profile#edit'
  post 'profile', to: 'profile#update'
   
  resources :users, only: :show
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

	devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :edit => "profile/edit" }
	resources :tournaments do
    post :attend, on: :member
    get 'net', to: 'tournament#show'
    post :approve_user, on: :member
    get :randomize_players, on: :collection
    resources :comments
  end

  root 'home#index'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_filter :authenticate_user!
  helper_method :mailbox, :conversation

  def create
    recipient_emails = conversation_params(:recipients).split(',')
    recipients = User.where(nickname: recipient_emails).all

    conversation = current_user.
      send_message(recipients, *conversation_params(:body, :subject)).conversation

    redirect_to conversation_path(conversation)
  end

  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :conversations
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
      when 0 then self
      when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end
end

app/views/conversations/_conversation.html.haml
%tbody
  = content_tag_for(:tr, conversation) do |conversation|
    %tr
      %td= link_to conversation.subject, conversation_path(conversation)
      %td= conversation.recipients.first.nickname
      %td= conversation.recipients.last.nickname
      %td= conversation.created_at.strftime("%d/%M/%Y at %H:%M:%S")
      %td
        - if conversation.is_completely_trashed?(current_user)
          %span.glyphicon.glyphicon-repeat
          = link_to 'Untrash', untrash_conversation_path(conversation), method: :post
        - else
          %span.glyphicon.glyphicon-trash
          = link_to 'Move to trash', trash_conversation_path(conversation), method: :post

app/views/conversations/_form.html.haml
%div{:style => "overflow-y: scroll; height:200px;"}
  %ol
    - User.all.each do |u|
      :javascript
        $(document).ready(function(){
          $("#pick_user a").click(function(){
            var value = $(this).html();
                var input = $('#conversation_recipients');
                input.val(value);
          });
        });
        
      #pick_user
        = link_to u.nickname, "#"
        
= simple_form_for :conversation, url: :conversations do |f|        
  -# Это будет чисто для пользователя, сюда вбиваем ник, а реально мыло пойдет в хидден филд
  
  = f.input :recipients #, collection: User.all, as: :select
  = f.input :subject
  = f.input :body, as: :text
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = f.button :submit, 'Cancel', type: :reset, class: 'btn-danger'

app/views/conversations/index.html.haml
= link_to :new_conversation do
  %button.btn.btn-primary
    %span.glyphicon.glyphicon-pencil
    Start Conversation
%hr
.row
  .col-sm-12.col-md-12
    %ul.nav.nav-tabs
      %li.active
        %a{"data-toggle" => "tab", :href => "#inbox"}
          %span.glyphicon.glyphicon-inbox
          Inbox
      %li
        %a{"data-toggle" => "tab", :href => "#sent"}
          %span.glyphicon.glyphicon-user
          Sent
      %li
        %a{"data-toggle" => "tab", :href => "#trash"}
          %span.glyphicon.glyphicon-tags
          Trash
    .tab-content
      #inbox.tab-pane.fade.in.active
        %table.table
          %caption Your inbox
          - if mailbox.inbox.any?
            %thead
              %tr
                %th Subject
                %th From
                %th To
                %th Date
                %th Actions
            = render collection: mailbox.inbox, partial: 'conversation'
          - else
            .alert.alert-warning{style: "margin-top:20px;"}
              There's no messages yet.
              = link_to :new_conversation do
                %button.btn.btn-default
                  %span.glyphicon.glyphicon-envelope
                  Message somebody?
              
      #sent.tab-pane.fade.in
        %table.table
          %caption Sent messages
          %thead
            %tr
              %th Subject
              %th From
              %th To
              %th Date
              %th Actions
          = render collection: mailbox.sentbox, partial: 'conversation'
      #trash.tab-pane.fade.in
        %table.table
          %caption Trash bin
          %thead
            %tr
              %th Subject
              %th From
              %th To
              %th Date
              %th Actions
          = render collection: mailbox.trash, partial: 'conversation'

app/views/conversations/new.html.haml
%h1 Start Conversation
= render 'form'

app/views/conversations/show.html.haml
%h1
  %small
    Message from
  = conversation.recipients.last.nickname
%table.table
  %caption= conversation.subject
  %thead
    %tr
      %th Subject
      %th Message
  %tbody
    = content_tag_for(:tr, conversation.receipts_for(current_user)) do |receipt|
      - message = receipt.message
      %tr
        %td{style: "width:20%"}= message.subject
        %td{style: "width:80%"}= message.body
      
= render 'messages/form', conversation: conversation