config/routes.rb
Rails.application.routes.draw do
  
  get 'contacts', to: "contacts#index"

  resources :posts
  resources :home do
    resources :posts
  end
	get 'profile', to: 'profile#edit'
  post 'profile', to: 'profile#update'
   
  resources :users, only: :show
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

	devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :edit => "profile/edit" }
	resources :tournaments do
    post :attend, on: :member
    get 'net', to: 'tournament#show'
    post :approve_user, on: :member
    get :randomize_players, on: :collection
    resources :comments
  end

  root 'home#index'

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  resourcify
  belongs_to :user

  has_many :comments, dependent: :destroy

	has_many :randomized_users
	has_many :entrances
	has_many :users, -> { select("*") }, :through => :entrances

  validates :name, presence: true

	has_attached_file :replay 
	#validates_attachment_content_type :replay, :content_type => /\Areplay\/.*\rep/
	validates_attachment_content_type :replay, :not => 'text/plain', :with => %r{\.(rep)$}i

  # Map Image
  has_attached_file :map_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://placehold.it/300x300"
  validates_attachment_content_type :map_image, :content_type => /\Aimage\/.*\Z/	

  scope :ended, -> { where('ending_at < ?', DateTime.now) }
  scope :reversed, -> { order('created_at DESC') }
  
  def ended?
    !ending_at.nil? && ending_at < DateTime.now
  end
  
  def running?
    !starting_at.nil? && starting_at <= DateTime.now and DateTime.now <= ending_at
  end
  
  def upcoming?
    !starting_at.nil? && starting_at > DateTime.now
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
	
  before_filter :authenticate_user!, only: [:new, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html, :js
  
  def index
    #TODO reversed scope
    @tournaments = Tournament.reversed.paginate(:page => params[:page], :per_page => 6)
  end

  def show
    @tournament = Tournament.find params[:id]
  end

  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = current_user.tournaments.new(tournament_params)
    if @tournament.save
      
      flash[:notice] = t('ui.message.ar.created')
      redirect_to :action => :show, :id => @tournament.id
    else
      render :action => :new
    end
  end

  def edit
    @tournament = Tournament.find params[:id]
  end

  def update
    @tournament = Tournament.find params[:id]
    if @tournament.update_attributes(tournament_params)
      
      flash[:notice] = t('ui.message.ar.updated')
      redirect_to :action => :show, :id => @tournament.id
    else
      render :action => :edit
    end
  end

  def destroy
    tournament = Tournament.find params[:id]
    tournament.destroy
    flash[:notice]= t('ui.message.ar.deleted')
    redirect_to :action => :index
  end

  def attend
    tournament = Tournament.find params[:id]
    tournament.users << current_user unless tournament.users.include?(current_user)

    redirect_to tournament_path tournament
  end
  
  def approve_users
    @tournament = Tournament.find params[:id]
    
    respond_to do |format|
      format.js { render layout: false }
    end
  end
  
  def approve_user
    #TODO
    #entrance = TournamentsUser.find(params[:id], params[:user_id])
    #entrance.approved = false
    #entrance.save
    respond_to do |format|
      format.js { render text: 'ok' }
    end
  end
  
  def randomize_players
    tournament = Tournament.find params[:id]
    tournament.users.shuffle << randomize_player #unless tournament.users.include?(current_user)

    redirect_to tournament_path tournament
  end
  
  private

    def tournament_params
      params.require(:tournament).permit(:map_link, :map_name, :name, :description, :starting_at, :ending_at, :attend, :replay, :player1, :player2, :map_image)
    end
end

app/views/tournaments/_approve_users_form.haml
- @tournament.users.each do |user|
  .row
    .col-md-9
      = user.email
    .col-md-3.text-right
    - if user.going?
      = link_to approve_user_tournament_path(@tournament, { user_id: user.id }), method: :post, remote: true do
        %span.glyphicon.glyphicon-thumbs-up
      %button.btn.btn-danger
        %span.glyphicon.glyphicon-thumbs-down

app/views/tournaments/_comments.haml
- if @tournament.comments.any?
  %h2 Comments
  - @tournament.comments.each do |comment|
    .media
      .media-left
        = link_to comment.user do
          = image_tag comment.user.avatar.url, class: "media-object img-thumbnail", style:"height:64px; width:64px;"
      .media-body
        %h4.media-heading
          = link_to comment.user do
            = comment.user.nickname
        = comment.body
        %hr
        - if comment.user_id == current_user.id
          = link_to tournament_comment_path(comment.tournament_id, comment.id), :method => 'delete' do
            Remove Comment
            %span.glyphicon.glyphicon-remove

app/views/tournaments/_description.haml
= @tournament.description

app/views/tournaments/_form.haml
:javascript
  $("button span.fa").addClass("glyphicon glyphicon-calendar");

= simple_form_for @tournament do |f|
  .row
    .col-md-3
      = f.input :name, autofocus: true
      = f.input :description, as: :text, :input_html => {:rows => 5}
    .col-md-3
      = f.input :player1, as: :string
      = f.input :player2, as: :string
    .col-md-3
      = f.input :map_name
      = f.input :map_link, :hint => "http://example.com/fighting_spirit_1_3.scx"
    .col-md-3
      = f.input :starting_at, as: :datetime_picker
      = f.input :ending_at, as: :datetime_picker
  .row
    .col-md-12
      = f.input :replay, as: :file
      = f.input :map_image, as: :file
  = f.button :submit, :class => "btn-primary"

app/views/tournaments/_map_and_attend.haml
= image_tag @tournament.map_image.url, {style: "width:100%", class: "thumbnail"}
-# if user_signed_in?
  = link_to attend_tournament_path(@tournament), method: :post, class: 'btn btn-block btn-primary' do
    %span.glyphicon.glyphicon-plus-sign
    Attend

app/views/tournaments/_players.haml
.alert.alert-success{:role => "alert", style: "margin-bottom:0;"}
  .text-center
    = @tournament.player1
%h2.text-center{style: "margin-top:0;"}
  %small
    \- VS -
.alert.alert-danger{:role => "alert"}
  .text-center
    = @tournament.player2

app/views/tournaments/approve_users.haml
-#= render 'approve_user_form'

app/views/tournaments/approve_users.js.haml
$('#approve-user-form').html("#{j (render 'approve_users_form')}");
$('#approve-user-form').modal('show');

app/views/tournaments/edit.haml
%h3 Edit tournament
= render 'form'

app/views/tournaments/index.haml
.row
  .col-md-2
    = link_to tournaments_path, class: 'btn btn-block btn-primary' do
      %span.glyphicon.glyphicon-refresh
      Refresh
  .col-md-8
    %h1.text-center{style: "margin:0 auto;"}
      Tournaments
      %br
      %small.text-center
        
        = @tournaments.count
        = "tournament".pluralize(@tournaments.count)
        up so far
  .col-md-2
    - if user_signed_in?
      - if current_user.has_role? :admin
        = link_to new_tournament_path, class: 'btn btn-block btn-success' do
          %span.glyphicon.glyphicon-plus
          New
- if @tournaments.any?
  %br
  - @tournaments.each_with_index do |tournament, index|
    .thumbnail  
      .row
        .col-md-2
          = image_tag "http://placehold.it/300x300", style: "width:100%;"
        .col-md-8
          .row
            .col-md-12
              %h1{style: "margin:0 auto;"}
                = link_to tournament do
                  = tournament.name
              - if tournament.starting_at.present?
                %small
                  %span.glyphicon.glyphicon-time  
                  = tournament.starting_at.strftime("%e %b at %H:%M")
                  - if tournament.ending_at.present?
                    \-
                    = tournament.ending_at.strftime("%e %b at %H:%M")
          .row
            .col-md-12
              %p= tournament.description
        .col-md-2
          - if user_signed_in?
            - if tournament.user_id == current_user.id
              = link_to tournament_path(tournament), class: 'btn btn-block btn-danger', method: :delete do
                %span{ :class => "glyphicon glyphicon-trash" }
                Remove
              = link_to edit_tournament_path(tournament), class: 'btn btn-block btn-default' do
                %span{ :class => "glyphicon glyphicon-pencil" }
                Edit
          = link_to tournament_path(tournament), class: 'btn btn-block btn-primary' do
            %span{ :class => "glyphicon glyphicon-plus" }
            Read More
  
- else
  .alert.alert-warning
    %h1
      = t('ui.alert.empty')
    = t('ui.alert.wdy')
    = link_to t('ui.alert.co'), new_tournament_path
    ?
.text-center
  = will_paginate @tournaments

app/views/tournaments/new.haml
%h3 New tournament
= render 'form'

app/views/tournaments/randomize_players_form.haml
- @tournament.users.each do |user|
  .row
    .col-md-9
      = user.email
    .col-md-3.text-right
    - if user.going?
      = link_to approve_user_tournament_path(@tournament, { user_id: user.id }), method: :post, remote: true do
        %span.glyphicon.glyphicon-thumbs-up
      %button.btn.btn-danger
        %span.glyphicon.glyphicon-thumbs-down

app/views/tournaments/show.haml
= link_to tournaments_path, class: 'btn btn-primary' do
  %span.glyphicon.glyphicon-chevron-left
  Tournaments
%div
  %ul.nav.nav-tabs{:role => "tablist"}
    %li.active{:role => "presentation"}
      %a{"aria-controls" => "details", "data-toggle" => "tab", :href => "#details", :role => "tab"} Details
    
    - if user_signed_in?
      - if current_user.has_role? :admin
        %li{:role => "presentation"}
          %a{"aria-controls" => "attending", "data-toggle" => "tab", :href => "#attending", :role => "tab"}
            %span.glyphicon.glyphicon-user
            Attending
  %h1
    = @tournament.name
    
    - if user_signed_in?
      .text-right
      - if @tournament.user.id == current_user.id
        = link_to edit_tournament_path(@tournament), class: 'btn-xs btn btn-default' do
          %span{ :class => "glyphicon glyphicon-pencil" }
          = t('ui.button.edit')
        = link_to tournament_path(@tournament), class: 'btn-xs btn btn-danger', method: :delete do
          %span{ :class => "glyphicon glyphicon-trash" }
          = t('ui.button.delete')

  .tab-content
    #details.active.tab-pane{:role => "tabpanel"}
      .row
        .col-md-6
          .row
            .col-md-6
              = render "map_and_attend"
            .col-md-6
              .panel.panel-default
                .panel-heading
                  %h3.panel-title Details
                .panel-body
                  = render "players"
          .row
            .col-md-12
              .panel.panel-default
                .panel-heading
                  %h3.panel-title Details
                .panel-body
                  = render "details"
          .row
            .col-md-12
              .panel.panel-default
                .panel-heading
                  %h3.panel-title Description
                .panel-body
                  = render "description"
        .col-md-6
          .row
            .col-md-12
              .panel.panel-default
                .panel-heading
                  %h3.panel-title Comments
                .panel-body
                  = render 'comments'
          .row
            .col-md-12
              .panel.panel-default
                .panel-heading
                  %h1.panel-title Add a Comment
                .panel-body
                  - if user_signed_in?
                    = simple_form_for([@tournament, @tournament.comments.build], html: { class: "form form-horizontal meme" }) do |f|
                      %p
                        = f.text_area :body, class: 'form-control'
                      %p
                        = f.button :submit do
                          %button.btn.btn-primary
                            Submit
                  - else
                    .alert.alert-info
                      Please
                      = link_to new_user_session_path do
                        login
                      or
                      = link_to new_user_registration_path do
                        register
                      to leave a comment!
              
    #attending.tab-pane{:role => "tabpanel"}
      - if user_signed_in?
        - if current_user.has_role? :admin
          .row
            .col-md-12
              %table.table.table-striped
                - @tournament.users.reverse.each_with_index do |e, index|
                  %thead
                    - if index == 0
                      %tr
                        %th #
                        %th AKA
                %tbody
                  - @tournament.users.reverse.each_with_index do |e, index|
                    %tr
                      %th{:scope => "row"}= index + 1
                      %td
                        = link_to e.nickname, user_path(e.id)