config/routes.rb
Rails.application.routes.draw do
  
  get 'contacts', to: "contacts#index"

  resources :posts
  resources :home do
    resources :posts
  end
	get 'profile', to: 'profile#edit'
  post 'profile', to: 'profile#update'
   
  resources :users, only: :show
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

	devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :edit => "profile/edit" }
	resources :tournaments do
    post :attend, on: :member
    get 'net', to: 'tournament#show'
    post :approve_user, on: :member
    get :randomize_players, on: :collection
    resources :comments
  end

  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  resourcify
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate_user!, only: [:new, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html, :js
  #geocoded_by :address
  
  def index
    #TODO reversed scope
    @posts = Post.order('created_at DESC').paginate(:page => params[:page], :per_page => 4)
  end

  def show
    @post = Post.find params[:id]
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = t('ui.message.ar.created')
      redirect_to :action => :show, :id => @post.id
    else
      render :action => :new
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    if @post.update_attributes(post_params)      
      flash[:notice] = t('ui.message.ar.updated')
      redirect_to :action => :show, :id => @post.id
    else
      render :action => :edit
    end
  end

  def destroy
    post = Post.find params[:id]
    post.destroy
    flash[:notice]= t('ui.message.ar.deleted')
    redirect_to :action => :index
  end
  
  private

    def post_params
      params.require(:post).permit(:name, :description)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.haml
= simple_form_for @post do |f|
  .row
    .col-md-12
      = f.input :name, autofocus: true
      = f.input :description, as: :wysihtml5, :input_html => {:rows => 25}
      = f.button :submit, :class => "btn-primary"

app/views/posts/edit.haml
%pre
  %h3 DEBUG
  = raw JSON.pretty_generate(current_user.attributes).gsub(" ","&nbsp;")
%h3 Edit Article
= render 'form'

app/views/posts/index.haml
= link_to posts_path, class: 'btn btn-primary' do
  %span.glyphicon.glyphicon-refresh
  Refresh
- if @posts.any?
  %h1.text-center News and updates:
  - @posts.each do |p|
    = link_to p do
      %h2= p.name
    %small
      %span.glyphicon.glyphicon-time
      = p.created_at.strftime("%-d %b at %H:%M")
    %p
      = p.description.split[0...100].join(' ').html_safe
      %br
      = link_to p do
        %span.glyphicon.glyphicon-menu-right
        Read More
    - if p != @posts.last 
      %hr
.text-center
  = will_paginate @posts, renderer: BootstrapPagination::Rails

app/views/posts/new.haml
%h3 New Article
= render 'form'

app/views/posts/show.haml
.row
  .col-md-12
    %h2
      = @post.name
      %br
      %small
        %span.glyphicon.glyphicon-time
        = @post.created_at.strftime("%-d %b at %H:%M")
    = @post.description.html_safe
 
    - if user_signed_in?
      - if current_user.has_role? :admin
        %hr
        = link_to edit_post_path(@post), class: 'btn btn-default', style: 'margin:0' do
          %span{ :class => "glyphicon glyphicon-pencil" }
          = t('ui.button.edit')
        = link_to post_path(@post), class: 'btn btn-danger', method: :delete, style: 'margin:0' do
          %span{ :class => "glyphicon glyphicon-trash" }
          = t('ui.button.delete')