config/routes.rb
Rails.application.routes.draw do
  
  get 'contacts', to: "contacts#index"

  resources :posts
  resources :home do
    resources :posts
  end
	get 'profile', to: 'profile#edit'
  post 'profile', to: 'profile#update'
   
  resources :users, only: :show
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

	devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :edit => "profile/edit" }
	resources :tournaments do
    post :attend, on: :member
    get 'net', to: 'tournament#show'
    post :approve_user, on: :member
    get :randomize_players, on: :collection
    resources :comments
  end

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
      can :attend, :tournaments
      # fix if wrong
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tournament
  belongs_to :user
end

app/models/entrance.rb
class Entrance < ActiveRecord::Base
  belongs_to :user
  belongs_to :tournament
end

app/models/post.rb
class Post < ActiveRecord::Base
  resourcify
  belongs_to :user
end

app/models/randomized_user.rb
class RandomizedUser < ActiveRecord::Base
  belongs_to :tournament
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  resourcify
  belongs_to :user

  has_many :comments, dependent: :destroy

	has_many :randomized_users
	has_many :entrances
	has_many :users, -> { select("*") }, :through => :entrances

  validates :name, presence: true

	has_attached_file :replay 
	#validates_attachment_content_type :replay, :content_type => /\Areplay\/.*\rep/
	validates_attachment_content_type :replay, :not => 'text/plain', :with => %r{\.(rep)$}i

  # Map Image
  has_attached_file :map_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://placehold.it/300x300"
  validates_attachment_content_type :map_image, :content_type => /\Aimage\/.*\Z/	

  scope :ended, -> { where('ending_at < ?', DateTime.now) }
  scope :reversed, -> { order('created_at DESC') }
  
  def ended?
    !ending_at.nil? && ending_at < DateTime.now
  end
  
  def running?
    !starting_at.nil? && starting_at <= DateTime.now and DateTime.now <= ending_at
  end
  
  def upcoming?
    !starting_at.nil? && starting_at > DateTime.now
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_messageable
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	validates_presence_of :nickname
  validates_uniqueness_of :nickname
	
	has_many :tournaments
  has_many :comments, through: :tournaments, dependent: :destroy
  has_many :posts
  has_many :entrances
  has_many :entrance_events, through: :entrances
  
  # Avatars
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "user-default.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  def name
    nickname
  end

  def mailboxer_email(object)
    nickname
  end
  
  def display_name
    "#{nickname}"
  end
  
  def profile_completed?
    !nickname.empty?
  end
  
  after_create :assign_default_role

  def assign_default_role
    add_role(:normal) if self.roles.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    #redirect_to main_app.root_url
    
    # loop check
		if session[:last_back] != request.env['HTTP_REFERER']
		  redirect_to :back, :alert => exception.message
		  session[:last_back] = request.env['HTTP_REFERER']
		else
		  # raise on error
		  redirect_to root_path # я просто оставлю это тут :action => :index
		  flash[:danger] = exception.message
		end
  end
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :nickname
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @tournament = Tournament.find(params[:tournament_id])
    @comment = @tournament.comments.create(comment_params)
    @comment.user = current_user
    @comment.save
    
    redirect_to tournament_path(@tournament)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    
    redirect_to @comment.tournament
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@posts = Post.order('created_at DESC').paginate(:page => params[:page], :per_page => 2)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate_user!, only: [:new, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html, :js
  #geocoded_by :address
  
  def index
    #TODO reversed scope
    @posts = Post.order('created_at DESC').paginate(:page => params[:page], :per_page => 4)
  end

  def show
    @post = Post.find params[:id]
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = t('ui.message.ar.created')
      redirect_to :action => :show, :id => @post.id
    else
      render :action => :new
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    if @post.update_attributes(post_params)      
      flash[:notice] = t('ui.message.ar.updated')
      redirect_to :action => :show, :id => @post.id
    else
      render :action => :edit
    end
  end

  def destroy
    post = Post.find params[:id]
    post.destroy
    flash[:notice]= t('ui.message.ar.deleted')
    redirect_to :action => :index
  end
  
  private

    def post_params
      params.require(:post).permit(:name, :description)
    end
end

app/controllers/profile_controller.rb
class ProfileController < UsersController
  def edit
  end

  def update
    if current_user.update_attributes(profile_params)
      flash[:notice]= t('ui.message.ar.updated')
      redirect_to user_path current_user
    else
      render :action => :edit
    end
  end

  private

    def profile_params
      params.require(:user).permit(:nickname, :about, :avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
        class: "alert fade in alert-#{type} #{tag_class}"
      }.merge(options)

      close_button = content_tag(:button, raw("&times;"), type: "button", class: "close", "data-dismiss" => "alert")

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg.html_safe, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Broodwar Gaming Portal
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = favicon_link_tag 'app/assets/images/favicon.png'
    = csrf_meta_tags
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css", :rel => "stylesheet"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %meta{:content => "initial-scale = 1.0,maximum-scale = 1.0", :name => "viewport"}/
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          -#%a.navbar-brand{:href => "#"}
          = link_to root_path, class:"navbar-brand" do
            = image_tag "logo.png", style: "height:64px"
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to tournaments_path do
                %span.glyphicon.glyphicon-screenshot
                Tournaments
            %li.active
              %li.page-scroll
                = link_to posts_path do
                  %span.glyphicon.glyphicon-book
                  News
              %li.page-scroll
                = link_to contacts_path do
                  %span.glyphicon.glyphicon-info-sign
                  Contacts
              
            
          - if user_signed_in?
            - if current_user.has_role? :admin
              %ul.nav.navbar-nav.navbar-right
                %li.dropdown
                  %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                    %span.glyphicon.glyphicon-dashboarde
                    Dashboard
                    %span.caret
                  %ul.dropdown-menu
                    %li
                      = link_to new_post_path do
                        %span.glyphicon.glyphicon-book
                        New post
                    %li    
                      = link_to new_tournament_path do
                        %span.glyphicon.glyphicon-screenshot
                        New tournament
                      
            %ul.nav.navbar-nav.navbar-right
              %li.dropdown
                %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  %span.glyphicon.glyphicon-tasks
                  Menu
                  %span.caret
                %ul.dropdown-menu
                  %li
                    = link_to conversations_path do
                      %span.glyphicon.glyphicon-envelope
                      Messages
                  %li
                    = link_to user_path(current_user) do
                      %span.glyphicon.glyphicon-user
                      Profile
                  %li
                    = link_to profile_path do
                      %span.glyphicon.glyphicon-cog
                      Settings
                  %li.divider{:role => "separator"}
                  %li
                    = link_to destroy_user_session_path, :method => :delete do
                      %span.glyphicon.glyphicon-off
                      Logout
          - else
            %ul.nav.navbar-nav.navbar-right
              %li
                = link_to new_user_session_path do
                  %span.glyphicon.glyphicon-user
                  Login
          - if user_signed_in?
            - if current_user.avatar.url.present?
              %ul.nav.navbar-nav.navbar-right
                = link_to current_user do
                  %li.dropdown{:class=> "img-circle", :style=> "background:url(#{current_user.avatar.url}); background-size:48px 48px;height:48px; width:48px; margin:8px;"}
                  -#= current_user.nickname
              
    -#%nav.navbar.navbar-default.navbar-fixed-top

              %li
                .dropdown{"aria-controls" => "profileCollapse", "aria-expanded" => "true", "data-target" => "#profileCollapse", "data-toggle" => "collapse", :class => "profile"}
                  %span.glyphicon.glyphicon-user
                   
                          
                

                    
                  
            
            
              %h4
                %small
                  Upcoming Game
                %br
                - Tournament.all.take(1).each do |t|
                  - if t.starting_at < DateTime.now
                    = link_to t.name, tournament_path(t)
    .container
      .row
        .col-md-12      
          = bootstrap_flash
          = yield                
      -#= (!t.starting_at.nil? && t.starting_at - DateTime.now)/36000
          
        %footer.footer
          .container
            %p.text-muted.text-center
              v. 0.4.1

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44943548-2', 'auto');
  ga('send', 'pageview');
  
:javascript
  $("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
  });

app/views/messages/_form.html.haml
= simple_form_for :message, url: reply_conversation_path(conversation) do |f|
  = f.input :subject
  = f.input :body
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = submit_tag 'Cancel', type: :reset, class: 'btn btn-danger'